version: '3'

services:

  # Prometheus Service
  prometheus:
    container_name: 'prometheus'
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - '9090:9090'

  # Grafana Service
  grafana:
    container_name: 'grafana'
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

  # K6 Service
  k6:
    container_name: 'k6'
    build:
      context: ./k6
      dockerfile: Dockerfile
    depends_on:
      - prometheus
      - grafana
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:9090/api/v1/write